# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "eb629f7ef2177c6f74d0e0da6b7f2749"
name = "SmartDiscovery AI"
application_url = "https://fdef-194-212-224-20.ngrok-free.app"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://fdef-194-212-224-20.ngrok-free.app/api/auth/callback",
  "https://fdef-194-212-224-20.ngrok-free.app/api/auth/online/callback"
]

[app_proxy]
url = "https://fdef-194-212-224-20.ngrok-free.app/api/proxy"
subpath = "smartdiscovery"
prefix = "apps"
