import { fileURLToPath } from 'node:url';
import fs from 'node:fs';
import path from 'node:path';
import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';

const rootDir = fileURLToPath(new URL('./', import.meta.url));

// ---------------------------------------------------------------------------
// .prisma/client shim — required because Prisma 7 generates its TypeScript
// client to a custom path (app/generated/prisma) instead of the default
// node_modules/.prisma/client directory. When @shopify/shopify-app-session-
// storage-prisma does require('@prisma/client'), Node resolves that to
// node_modules/@prisma/client/default.js, which in turn does
// require('.prisma/client/default') — resolving to node_modules/.prisma/
// client/default. Without this shim that file doesn't exist, causing a
// MODULE_NOT_FOUND crash at suite load time.
//
// The shim re-exports the relevant runtime symbols from @prisma/client/runtime
// /client (PrismaClientKnownRequestError etc.) under a Prisma namespace, which
// is all the session-storage package actually needs at runtime.
//
// Placement: this runs at config-eval time (top-level module scope) because
// Vitest's fork-pool workers natively require() the session-storage package
// before any globalSetup or setupFiles hook executes — the file must exist on
// disk before any worker boots. The server.deps.inline block below (which
// processes the package through the Vite pipeline) does NOT intercept this
// native CJS require; only the on-disk shim can satisfy it.
// ---------------------------------------------------------------------------
const shimDir = path.join(rootDir, 'node_modules/.prisma/client');
const shimFile = path.join(shimDir, 'default.js');

if (!fs.existsSync(shimFile)) {
  fs.mkdirSync(shimDir, { recursive: true });
  fs.writeFileSync(
    shimFile,
    [
      '// Auto-generated by vitest.config.ts — DO NOT EDIT.',
      '// Mirrors what `prisma generate` writes when using the default output path.',
      '// Prisma 7 with a custom output skips this file; we create it so that',
      '// @shopify/shopify-app-session-storage-prisma can require("@prisma/client").',
      "'use strict';",
      "const runtime = require('@prisma/client/runtime/client');",
      'const Prisma = {',
      '  PrismaClientKnownRequestError: runtime.PrismaClientKnownRequestError,',
      '  PrismaClientUnknownRequestError: runtime.PrismaClientUnknownRequestError,',
      '  PrismaClientRustPanicError: runtime.PrismaClientRustPanicError,',
      '  PrismaClientInitializationError: runtime.PrismaClientInitializationError,',
      '  PrismaClientValidationError: runtime.PrismaClientValidationError,',
      '  Decimal: runtime.Decimal,',
      '  sql: runtime.sqltag,',
      '  empty: runtime.empty,',
      '  join: runtime.join,',
      '  raw: runtime.raw,',
      '};',
      'module.exports = { Prisma, ...runtime };',
      '',
    ].join('\n'),
  );
}

export default defineConfig({
  root: rootDir,
  plugins: [react()],
  test: {
    environment: 'jsdom',
    globals: true,
    setupFiles: ['./vitest.setup.ts'],
    include: [
      '**/*.{test,spec}.?(c|m)[jt]s?(x)',
      '**/*.integration-test.?(c|m)[jt]s?(x)',
    ],
    server: {
      deps: {
        // Inlining processes this CJS package through the Vite pipeline so
        // the resolve.alias regex below can intercept the `@prisma/client`
        // specifier that Vite sees in the package's source. Without inlining,
        // Vitest externalizes node_modules and the alias never runs.
        //
        // IMPORTANT: inlining does NOT intercept the package's native CJS
        // require('@prisma/client') call that Node evaluates at worker boot.
        // That require is satisfied by the on-disk node_modules/.prisma/client/
        // default.js shim written at the top of this file. Both mechanisms are
        // required — deleting either one reintroduces the MODULE_NOT_FOUND crash.
        inline: ['@shopify/shopify-app-session-storage-prisma'],
      },
    },
  },
  resolve: {
    alias: [
      // Mirrors next.config.ts: Prisma 7 generates the client to
      // app/generated/prisma, so @prisma/client must resolve to the
      // re-export shim instead of the stub npm package.
      // Use a regex anchored to the exact specifier so that subpath imports
      // like @prisma/client/runtime/client are NOT intercepted — Vite's string
      // aliases are prefix-matched and would redirect those subpaths to the
      // shim file path, causing resolution errors.
      {
        find: /^@prisma\/client$/,
        replacement: fileURLToPath(
          new URL('./lib/prisma-npm-reexport.ts', import.meta.url),
        ),
      },
      { find: '@', replacement: rootDir },
    ],
  },
});
